services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./lua/:/usr/local/openresty/nginx/lua/
  test:
    build:
      context: .
      dockerfile: DockerfileTest
    volumes:
      - ./lua:/usr/local/openresty/nginx/lua
    command: ["busted", "."]